const wordDatabase = {
2: [
  { word: "DO", hint: "perform an action", emojis: ["✅","🎭","⚙️"], hint2: "executar uma ação" },
  { word: "IF", hint: "introduce a condition", emojis: ["❓","🔄","🤔"], hint2: "introduzir uma condição" },
  { word: "AS", hint: "compare or equal", emojis: ["🟰","🔗","📊"], hint2: "comparar ou igualar" },
  { word: "AT", hint: "indicate location or time", emojis: ["📍","🕒","🏠"], hint2: "indicar localização ou horário" },
  { word: "BY", hint: "indicate the agent", emojis: ["👤","➡️","📝"], hint2: "indicar o agente" },
  { word: "HE", hint: "male pronoun", emojis: ["👨","🧑","🚹"], hint2: "pronome masculino" },
  { word: "ME", hint: "first-person object pronoun", emojis: ["🙋","👤","🫵"], hint2: "pronome pessoal oblíquo" },
  { word: "WE", hint: "first-person plural pronoun", emojis: ["👥","🤝","👫"], hint2: "pronome plural de primeira pessoa" },
  { word: "US", hint: "object pronoun for we", emojis: ["👥","👉","🤲"], hint2: "pronome oblíquo para nós" },
  { word: "ON", hint: "indicate position or state", emojis: ["🔛","📌","🛑"], hint2: "indicar posição ou estado" },
  { word: "IN", hint: "inside something", emojis: ["📦","🏠","🔒"], hint2: "dentro de algo" },
  { word: "TO", hint: "indicate direction or purpose", emojis: ["➡️","🎯","✉️"], hint2: "indicar direção ou propósito" },
  { word: "OF", hint: "express belonging or origin", emojis: ["📖","🏷️","🌍"], hint2: "expressar pertencimento ou origem" },
  { word: "OR", hint: "express choice", emojis: ["🔄","❔","⚖️"], hint2: "expressar escolha" },
  { word: "AN", hint: "indefinite article before vowel", emojis: ["🔡","📰","📖"], hint2: "artigo indefinido antes de vogal" },
  { word: "UP", hint: "toward a higher position", emojis: ["⬆️","🏔️","🚀"], hint2: "para uma posição mais alta" },
  { word: "GO", hint: "move or proceed", emojis: ["🏃","🚗","➡️"], hint2: "mover-se ou prosseguir" },
  { word: "NO", hint: "negative response or refusal", emojis: ["❌","🙅","🚫"], hint2: "resposta negativa ou recusa" },
  { word: "SO", hint: "therefore or to such an extent", emojis: ["➡️","🤷","🔚"], hint2: "portanto ou em tal grau" },
  { word: "BE", hint: "exist or live", emojis: ["🧬","🌱","⚒️"], hint2: "existir ou viver" }
],  
3: [
    { word: "SUN", hint: "bright object in sky", emojis: ["🌞","🔥","🌅"], hint2: "Objeto brilhante no céu" },
    { word: "CAT", hint: "small furry animal", emojis: ["🐾","😺","🛏️"], hint2: "Animal doméstico felino" },
    { word: "MAP", hint: "shows directions", emojis: ["🗺️","🧭","🧳"], hint2: "Representa rotas e caminhos" },
    { word: "PEN", hint: "used to write", emojis: ["✍️","🖋️","📖"], hint2: "Instrumento para escrever" },
    { word: "KEY", hint: "opens locks", emojis: ["🔑","🛅","🚪"], hint2: "Abre fechaduras e trancas" },
    { word: "BOX", hint: "cube for storing things", emojis: ["📦","📥","📤"], hint2: "Caixa para guardar objetos" },
    { word: "WEB", hint: "online or spider trap", emojis: ["🌐","🕷️","🧶"], hint2: "Rede digital ou teia física" },
    { word: "FAN", hint: "blows air or supporter", emojis: ["🌀","🙌","🎐"], hint2: "Aparelho que circula ar" },
    { word: "HAT", hint: "worn on head", emojis: ["🎩","🧢","👒"], hint2: "Cobre a cabeça do usuário" },
    { word: "JAM", hint: "sweet spread or traffic", emojis: ["🍓","🚗","🎼"], hint2: "Doce de frutas preparado" },
    { word: "LOG", hint: "piece of wood or record", emojis: ["🌲","📒","🪵"], hint2: "Registro ou pedaço de madeira" },
    { word: "ICE", hint: "frozen water", emojis: ["❄️","🧊","🥶"], hint2: "Água no estado sólido frio" },
    { word: "NET", hint: "catches or connects", emojis: ["🎣","🕸️","📡"], hint2: "Rede para capturar ou ligar" },
    { word: "TAP", hint: "water source or touch", emojis: ["🚰","👆","🔊"], hint2: "Torneira para liberar água" },
    { word: "EGG", hint: "oval food from birds", emojis: ["🥚","🐣","🍳"], hint2: "Alimento oval de aves" },
    { word: "BUG", hint: "small insect or error", emojis: ["🐛","💻","🪲"], hint2: "Inseto ou falha em sistema" },
    { word: "GAS", hint: "fuel or state of matter", emojis: ["⛽","💨","🔥"], hint2: "Combustível em estado gasoso" },
    { word: "ZIP", hint: "fastener or compress", emojis: ["🧷","🧳","🗜️"], hint2: "Fecho rápido ou compactador" },
    { word: "TOY", hint: "for play", emojis: ["🧸","🎲","🛷"], hint2: "Objeto destinado à brincadeira" },
    { word: "POD", hint: "container or seed case", emojis: ["🌱","🚀","📦"], hint2: "Invólucro de sementes ou cápsula" }
  ],
  4: [
    { word: "BOOK", hint: "contains pages", emojis: ["📖","📚","🔖"], hint2: "Conjunto de páginas encadernadas" },
    { word: "TREE", hint: "plant with branches", emojis: ["🌳","🍃","🪵"], hint2: "Planta grande com galhos" },
    { word: "FIRE", hint: "hot and bright", emojis: ["🔥","🚒","🔥"], hint2: "Combustão que gera calor" },
    { word: "ROAD", hint: "path for cars", emojis: ["🛣️","🚗","🛤️"], hint2: "Via para circulação de veículos" },
    { word: "TIME", hint: "constant flow", emojis: ["⏰","🕰️","⏳"], hint2: "Medida contínua da duração" },
    { word: "GOLD", hint: "precious metal", emojis: ["💰","🪙","✨"], hint2: "Metal valioso e amarelo" },
    { word: "LOCK", hint: "secures something", emojis: ["🔒","🗝️","🚪"], hint2: "Mecanismo para proteger algo" },
    { word: "BELL", hint: "makes sound", emojis: ["🔔","📯","📣"], hint2: "Instrumento que emite toque" },
    { word: "HAND", hint: "part of body", emojis: ["✋","🖐️","📿"], hint2: "Extremidade do braço humano" },
    { word: "RING", hint: "round object or jewelry", emojis: ["💍","📞","🎯"], hint2: "Argola circular ou joia" },
    { word: "WIND", hint: "moving air", emojis: ["🌬️","🍃","🎐"], hint2: "Corrente de ar natural" },
    { word: "MILK", hint: "white drink", emojis: ["🥛","🐄","🍼"], hint2: "Bebida branca de mamíferos" },
    { word: "SINK", hint: "wash area or go down", emojis: ["🚿","📉","🧽"], hint2: "Área para lavar utensílios" },
    { word: "BALL", hint: "round toy or object", emojis: ["⚽","🏀","🎾"], hint2: "Objeto esférico para jogos" },
    { word: "CODE", hint: "secret or programming", emojis: ["🔐","💻","🧠"], hint2: "Sistema de símbolos ou software" },
    { word: "SHIP", hint: "large boat", emojis: ["🚢","⚓","🌊"], hint2: "Embarcação de grande porte" },
    { word: "NOTE", hint: "short message or tone", emojis: ["📝","🎵","🎶"], hint2: "Mensagem breve ou sinal sonoro" },
    { word: "CARD", hint: "paper rectangle", emojis: ["🃏","💳","🎴"], hint2: "Retângulo de papel informativo" },
    { word: "MOON", hint: "night light in sky", emojis: ["🌕","🌑","🌙"], hint2: "Satélite natural da Terra" },
    { word: "DESK", hint: "work surface", emojis: ["🪑","🖥️","📚"], hint2: "Móvel usado para trabalhar" }
  ],
  5: [
    { word: "CHAIR", hint: "for sitting", emojis: ["🪑","🪵","🧍"], hint2: "Móvel para sentar pessoas" },
    { word: "CLOUD", hint: "in the sky", emojis: ["☁️","🌥️","⛅"], hint2: "Formação de vapor no céu" },
    { word: "LIGHT", hint: "bright or not heavy", emojis: ["💡","🌟","✨"], hint2: "Iluminação ou leveza" },
    { word: "BREAD", hint: "baked food", emojis: ["🍞","🥖","🧈"], hint2: "Alimento assado de trigo" },
    { word: "TABLE", hint: "flat surface", emojis: ["🍽️","📚","🪑"], hint2: "Superfície plana com pernas" },
    { word: "DANCE", hint: "rhythmic movement", emojis: ["💃","🎶","🕺"], hint2: "Movimento corporal ritmado" },
    { word: "PAINT", hint: "color something", emojis: ["🎨","🖌️","🧽"], hint2: "Aplicar cor em superfícies" },
    { word: "TRAIN", hint: "transport on tracks", emojis: ["🚆","🛤️","🚉"], hint2: "Trem para transportar pessoas" },
    { word: "PHONE", hint: "used to call", emojis: ["📞","📱","📡"], hint2: "Dispositivo para comunicação" },
    { word: "GRASS", hint: "green ground cover", emojis: ["🌱","🌾","🦗"], hint2: "Plantas rasteiras verdes" },
    { word: "PLANT", hint: "grows from soil", emojis: ["🌿","🪴","🌼"], hint2: "Organismo que cresce no solo" },
    { word: "FRUIT", hint: "sweet natural snack", emojis: ["🍎","🍉","🍇"], hint2: "Parte comestível da planta" },
    { word: "WATCH", hint: "time device", emojis: ["⌚","🕓","👀"], hint2: "Aparelho para ver horas" },
    { word: "ANGEL", hint: "holy being", emojis: ["😇","✨","🕊️"], hint2: "Ser celestial protetor" },
    { word: "BEACH", hint: "sandy shore", emojis: ["🏖️","🌊","⛱️"], hint2: "Faixa de areia à beira-mar" },
    { word: "FLAME", hint: "burning fire", emojis: ["🔥","🕯️","🪔"], hint2: "Parte viva do fogo queimando" },
    { word: "SLEEP", hint: "rest at night", emojis: ["🛌","💤","🌙"], hint2: "Estado de repouso corporal" },
    { word: "WATER", hint: "essential liquid", emojis: ["💧","🚰","🌊"], hint2: "Líquido vital para seres vivos" },
    { word: "TIGER", hint: "striped wild cat", emojis: ["🐅","🌿","👀"], hint2: "Felino selvagem listrado" },
    { word: "BRUSH", hint: "for hair or paint", emojis: ["🖌️","🪮","🧼"], hint2: "Ferramenta de cerdas flexíveis" }
  ],
  6: [
    { word: "CIRCLE", hint: "round shape", emojis: ["🔵","🌀","🎯"], hint2: "Figura geométrica redonda" },
    { word: "ROCKET", hint: "flies to space", emojis: ["🚀","🌌","🛰️"], hint2: "Veículo que vai ao espaço" },
    { word: "CASTLE", hint: "old fortified building", emojis: ["🏰","🛡️","⛓️"], hint2: "Construção fortificada antiga" },
    { word: "WINDOW", hint: "opening in wall", emojis: ["🪟","🌤️","🏡"], hint2: "Abertura para entrada de luz" },
    { word: "POCKET", hint: "small fabric holder", emojis: ["👖","📎","📩"], hint2: "Compartimento costurado em roupa" },
    { word: "BOTTLE", hint: "holds liquid", emojis: ["🍼","🍾","🥤"], hint2: "Recipiente para líquidos" },
    { word: "ANIMAL", hint: "living creature", emojis: ["🐾","🐘","🐒"], hint2: "Ser vivo que se move" },
    { word: "LAPTOP", hint: "portable computer", emojis: ["💻","🔋","👜"], hint2: "Computador leve e portátil" },
    { word: "MAGNET", hint: "attracts metal", emojis: ["🧲","⚙️","🪙"], hint2: "Elemento que atrai metais" },
    { word: "CARPET", hint: "floor cover", emojis: ["🧶","🛋️","🪄"], hint2: "Tecido para revestir piso" },
    { word: "FOREST", hint: "lots of trees", emojis: ["🌲","🌳","🌿"], hint2: "Extensa área de árvores" },
    { word: "BRIDGE", hint: "connects two sides", emojis: ["🌉","🛤️","⛓️"], hint2: "Estrutura sobre obstáculo" },
    { word: "TICKET", hint: "for entry", emojis: ["🎟️","✈️","🚆"], hint2: "Documento para acesso" },
    { word: "CANDLE", hint: "gives light when lit", emojis: ["🕯️","🔥","🌙"], hint2: "Fonte de luz com cera" },
    { word: "PUZZLE", hint: "brain game", emojis: ["🧩","🧠","❓"], hint2: "Desafio para exercitar mente" },
    { word: "MARKET", hint: "place to buy things", emojis: ["🛒","📦","💳"], hint2: "Local de compra e venda" },
    { word: "MONKEY", hint: "playful animal", emojis: ["🐒","🍌","🙈"], hint2: "Primate travesso e ágil" },
    { word: "DRAWER", hint: "where things are kept", emojis: ["🧰","🗄️","🔎"], hint2: "Compartimento de móvel" }
  ],
  7: [
    { word: "JOURNEY", hint: "long travel from one place to another", emojis: ["🧳","🗺️","🚉"], hint2: "Viagem longa entre locais" },
    { word: "DIGITAL", hint: "related to computers or tech", emojis: ["💻","🔢","🌐"], hint2: "Referente à tecnologia eletrônica" },
    { word: "MONSTER", hint: "scary imaginary creature", emojis: ["👹","👣","🌑"], hint2: "Criatura imaginária assustadora" },
    { word: "CAPITAL", hint: "main city of a country", emojis: ["🏙️","🎓","💵"], hint2: "Cidade principal de um país" },
    { word: "HARVEST", hint: "gathering crops", emojis: ["🌾","🌽","🧺"], hint2: "Colheita de produtos agrícolas" },
    { word: "JUSTICE", hint: "fair treatment or law", emojis: ["⚖️","🧑‍⚖️","📜"], hint2: "Ato de tratar com equidade" },
    { word: "FASHION", hint: "popular style or trend", emojis: ["👗","🧵","📸"], hint2: "Estilo popular de vestuário" },
    { word: "FREEDOM", hint: "state of being free", emojis: ["🕊️","🔓","🌎"], hint2: "Condicionamento de estar livre" },
    { word: "BLANKET", hint: "soft cover for warmth", emojis: ["🛌","🧸","🌙"], hint2: "Cobertor macio para aquecer" },
    { word: "CHARGER", hint: "powers devices", emojis: ["🔋","⚡","📱"], hint2: "Carrega baterias de aparelhos" },
    { word: "CRUMBLE", hint: "fall apart", emojis: ["🫧","🍪","🧂"], hint2: "Desmanchar em pequenos pedaços" },
    { word: "DIAMOND", hint: "precious shiny stone", emojis: ["💎","✨","🔺"], hint2: "Pedra preciosa e reluzente" },
    { word: "FANTASY", hint: "magical story", emojis: ["🐉","🌌","📚"], hint2: "Narrativa com elementos mágicos" },
    { word: "BIOLOGY", hint: "study of life", emojis: ["🧬","🔬","🦠"], hint2: "Ciência que estuda seres vivos" },
    { word: "THEATER", hint: "place for shows", emojis: ["🎭","🎬","🎟️"], hint2: "Local para apresentações artísticas" },
    { word: "PIRATE", hint: "sea thief", emojis: ["☠️","🏴‍☠️","⚓"], hint2: "Ladrão que atua no mar" },
    { word: "MONITOR", hint: "screen or observer", emojis: ["🖥️","👁️","📡"], hint2: "Tela de exibição ou vigilante" },
    { word: "TRAFFIC", hint: "many vehicles on road", emojis: ["🚗","🚦","🛑"], hint2: "Fluxo intenso de veículos" },
    { word: "TEACHER", hint: "someone who teaches", emojis: ["🍎","📚","🧑‍🏫"], hint2: "Profissional que ministra aulas" },
    { word: "DECODER", hint: "reveals hidden text", emojis: ["🔐","📜","🕵️"], hint2: "Ferramenta para decifrar códigos" }
  ],
  8: [
    { word: "CALENDAR", hint: "shows dates", emojis: ["📅","🕒","🗓️"], hint2: "Organiza dias e meses do ano" },
    { word: "SECURITY", hint: "protection from harm", emojis: ["🛡️","🔐","👮"], hint2: "Proteção contra ameaças" },
    { word: "ELEPHANT", hint: "large animal with trunk", emojis: ["🐘","🌿","🦴"], hint2: "Grande mamífero com tromba" },
    { word: "PLATFORM", hint: "raised flat surface", emojis: ["🪜","🛤️","🚉"], hint2: "Superfície elevada para acesso" },
    { word: "HOSPITAL", hint: "place for medical help", emojis: ["🏥","💉","🩺"], hint2: "Local para atendimento médico" },
    { word: "UMBRELLA", hint: "used in rain", emojis: ["☂️","💧","🌧️"], hint2: "Protege da chuva e sol" },
    { word: "NOTEBOOK", hint: "paper for writing", emojis: ["📒","✍️","🧠"], hint2: "Caderno para anotações" },
    { word: "DELIVERY", hint: "transport of goods", emojis: ["📦","🚚","📬"], hint2: "Serviço de envio de encomendas" },
    { word: "OPERATOR", hint: "controls a machine", emojis: ["📞","⚙️","👷"], hint2: "Pessoa que manuseia máquinas" },
    { word: "BACKPACK", hint: "carried on the back", emojis: ["🎒","🌄","👟"], hint2: "Mochila para transportar itens" },
    { word: "FESTIVAL", hint: "public celebration", emojis: ["🎉","🎶","🍻"], hint2: "Evento festivo ao ar livre" },
    { word: "INTERNET", hint: "global web", emojis: ["🌐","💻","📡"], hint2: "Rede mundial de computadores" },
    { word: "BUILDING", hint: "large structure", emojis: ["🏢","🏗️","🚪"], hint2: "Estrutura construída para uso" },
    { word: "DAUGHTER", hint: "female child", emojis: ["👧","🧬","👨‍👩‍👧"], hint2: "Filha em relação aos pais" },
    { word: "PAINTING", hint: "artwork with colors", emojis: ["🖼️","🎨","🧵"], hint2: "Obra artística em tinta" },
    { word: "BASEBALL", hint: "bat-and-ball game", emojis: ["⚾","🏃","🧢"], hint2: "Jogo de rebatidas e corrida" },
    { word: "TRIANGLE", hint: "three-sided shape", emojis: ["🔺","📐","🎯"], hint2: "Figura geométrica de três lados" },
    { word: "SANDWICH", hint: "layers of food", emojis: ["🥪","🍗","🍅"], hint2: "Alimento com recheio entre pães" },
    { word: "MEDICINE", hint: "used for healing", emojis: ["💊","🧬","🩺"], hint2: "Substância para tratar doenças" },
    { word: "SNAPSHOT", hint: "quick photo", emojis: ["📸","⚡","🖼️"], hint2: "Foto rápida de um momento" }
  ],
  9: [
    { word: "ADVENTURE", hint: "exciting experience", emojis: ["🧗","🧭","🌋"], hint2: "Experiência cheia de emoção" },
    { word: "EQUIPMENT", hint: "necessary tools", emojis: ["⚙️","🎒","🧰"], hint2: "Conjunto de ferramentas úteis" },
    { word: "KNOWLEDGE", hint: "info and understanding", emojis: ["🧠","📚","🔍"], hint2: "Conjunto de informações úteis" },
    { word: "VOLCANOES", hint: "lava mountains", emojis: ["🌋","🔥","🌫️"], hint2: "Montanhas que expelem lava" },
    { word: "TELEPHONE", hint: "device to talk", emojis: ["📞","👂","📲"], hint2: "Aparelho para fazer chamadas" },
    { word: "CHOCOLATE", hint: "sweet brown food", emojis: ["🍫","🤎","👅"], hint2: "Doce feito de cacau" },
    { word: "INFECTION", hint: "illness from germs", emojis: ["🦠","🤒","🧼"], hint2: "Doença causada por microrganismos" },
    { word: "MAGAZINE", hint: "printed periodical", emojis: ["📖","📰","🗞️"], hint2: "Publicação impressa periódica" },
    { word: "FIREFIGHT", hint: "exchange of shots", emojis: ["🔫","🔥","🚨"], hint2: "Troca intensa de disparos" },
    { word: "BLUEPRINT", hint: "architectural plan", emojis: ["📐","📏","🏗️"], hint2: "Desenho técnico de construção" },
    { word: "NAVIGATOR", hint: "guides direction", emojis: ["🧭","🗺️","👨‍✈️"], hint2: "Pessoa que orienta rotas" },
    { word: "DISCOVERY", hint: "new finding", emojis: ["🔍","🧬","🚀"], hint2: "Encontrar algo anteriormente desconhecido" },
    { word: "ECOSYSTEM", hint: "nature balance", emojis: ["🌿","🌊","🐾"], hint2: "Conjunto de seres e ambiente" },
    { word: "DETECTIVE", hint: "investigates things", emojis: ["🕵️‍♂️","🔎","📜"], hint2: "Profissional que soluciona crimes" },
    { word: "HOUSEWORK", hint: "chores at home", emojis: ["🧹","🧺","🏠"], hint2: "Tarefas diárias de limpeza" },
    { word: "REHEARSAL", hint: "practice performance", emojis: ["🎭","🎬","🔁"], hint2: "Preparação antes de apresentação" },
    { word: "RECYCLING", hint: "reusing waste", emojis: ["🔄","♻️","🗑️"], hint2: "Processo de reaproveitar resíduos" },
    { word: "STORYLINE", hint: "plot of story", emojis: ["📚","🎞️","🧠"], hint2: "Enredo que guia a narrativa" }
  ],
  10: [
    { word: "NEWSPAPER", hint: "daily printed news", emojis: ["🗞️","📆","📜"], hint2: "Publicação diária de notícias" },
    { word: "ASTRONAUT", hint: "space traveler", emojis: ["🧑‍🚀","🌌","🚀"], hint2: "Pessoa que viaja ao espaço" },
    { word: "CALCULATOR", hint: "math machine", emojis: ["🧮","➗","📱"], hint2: "Dispositivo para cálculos" },
    { word: "BASKETBALL", hint: "hoop sport", emojis: ["🏀","⛹️‍♂️","🎯"], hint2: "Esporte com bola e cesta" },
    { word: "VOLLEYBALL", hint: "net game", emojis: ["🏐","🏖️","🤾"], hint2: "Jogo com bola e rede" },
    { word: "WATERMELON", hint: "juicy fruit", emojis: ["🍉","💧","🍽️"], hint2: "Fruto grande e suculento" },
    { word: "BINOCULARS", hint: "to see far", emojis: ["🔭","👁️","🌄"], hint2: "Instrumento para visão distante" },
    { word: "CONTROLLER", hint: "gaming device", emojis: ["🎮","🕹️","👾"], hint2: "Dispositivo para controlar jogos" },
    { word: "WHITEBOARD", hint: "erasable surface", emojis: ["🧽","🖍️","📐"], hint2: "Superfície apagável para escrita" },
    { word: "CLASSROOM", hint: "room for learning", emojis: ["📚","🏫","✏️"], hint2: "Ambiente destinado a aulas" },
    { word: "HEADPHONES", hint: "for listening", emojis: ["🎧","🔊","🎵"], hint2: "Aparelho para ouvir áudio" },
    { word: "SPAGHETTI", hint: "Italian pasta", emojis: ["🍝","🇮🇹","🍴"], hint2: "Massa longa de origem italiana" },
    { word: "GOVERNMENT", hint: "ruling body", emojis: ["🏛️","📜","⚖️"], hint2: "Autoridade máxima de governo" },
    { word: "RESTAURANT", hint: "food place", emojis: ["🍽️","🧾","👨‍🍳"], hint2: "Estabelecimento de refeições" },
    { word: "RESOLUTION", hint: "goal or clarity", emojis: ["🎯","📺","🗒️"], hint2: "Objetivo ou nitidez de imagem" },
    { word: "TECHNICIAN", hint: "skilled worker", emojis: ["🛠️","🔌","🧰"], hint2: "Especialista em manutenção técnica" },
    { word: "PLAYGROUND", hint: "kids play area", emojis: ["🛝","🏃","🎠"], hint2: "Local de diversão infantil" },
    { word: "LIGHTHOUSE", hint: "sea light tower", emojis: ["🌊","🚨","🏠"], hint2: "Torre luminosa para navegação" },
    { word: "TYPEWRITER", hint: "old writing tool", emojis: ["⌨️","📇","🖋️"], hint2: "Máquina antiga de digitar" },
    { word: "PROGRAMMING", hint: "code creation", emojis: ["💻","👨‍💻","📂"], hint2: "Processo de criar softwares" }
  ]
};
